In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
preprocess_url = 'https://kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3'
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/bert-en-uncased-l-12-h-768-a-12/versions/2"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()


dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [ ]:
bert_model = hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'pooled_output', 'default'])

In [ ]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[ 0.31700474, -0.00897161,  0.9470521 , ..., -0.7634885 ,
         0.16718054,  0.9982938 ],
       [ 0.3991409 , -0.14203501,  0.9058576 , ..., -0.78319436,
         0.17452335,  0.9984515 ]], dtype=float32)>

In [ ]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.80176634,  0.32361233,  0.06374362, ...,  0.16129759,
         -0.40045106, -0.5926615 ],
        [ 0.12236653, -0.02574404,  0.33795908, ...,  0.4220083 ,
         -0.00308669, -0.01367626],
        [-0.22754873,  0.13265473,  0.12623407, ..., -0.13245113,
         -0.29856133, -0.65101933],
        ...,
        [-0.0969215 ,  0.29766482,  0.28932047, ..., -0.09318282,
         -0.08340856,  0.21456768],
        [-0.2273308 ,  0.42583904,  0.0860441 , ...,  0.00257993,
          0.02146193,  0.2590342 ],
        [-0.22111098,  0.7789582 , -0.07339074, ...,  0.01744242,
         -0.07840022, -0.22917928]],

       [[ 0.05904213, -0.21204117, -0.13617851, ...,  0.43750256,
          0.5026955 , -0.35996336],
        [ 0.6707301 ,  0.14048877, -0.09224142, ...,  0.42108783,
          0.41119042, -0.5584124 ],
        [ 0.17798199, -0.49039   , -0.38667142, ...,  0.1257011 ,
         -0.2774938 , -0.15996684],
        ...,

In [ ]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07753128, -0.13169813, -0.12158287, ..., -0.2069684 ,
         -0.08625421,  0.03867288],
        [ 0.4165198 , -0.5702618 ,  0.30443764, ...,  1.0894068 ,
         -1.1624614 ,  0.31072158],
        [-0.6930369 , -1.03197   , -0.2733961 , ...,  0.5024312 ,
          0.09017463,  0.08964971],
        ...,
        [ 0.6270519 ,  0.44989935,  0.42121613, ..., -0.26613608,
          0.3644551 , -0.37089464],
        [ 0.68282175,  0.548256  ,  0.34665585, ..., -0.29157376,
          0.39371547, -0.2907476 ],
        [ 0.6804481 ,  0.5809116 ,  0.3258676 , ..., -0.17651248,
          0.447802  , -0.24795158]],

       [[ 0.02516399, -0.16400944, -0.04662891, ..., -0.2618655 ,
         -0.11140703,  0.15489224],
        [ 0.37214527,  0.7362576 , -0.37717193, ...,  0.6425172 ,
         -0.6226271 ,  0.05394955],
        [-1.3278612 , -0.0473671 ,  0.47504824, ...,  0.01998842,
         -0.4994462 ,  1.6198301 ],
        ...,